### ISSUE TITLE
problem fuzz+solver description to allow for env vars + validator

### ISSUE THREAD

**Issue by sunsetkookaburra** [ProgSoc/FuzzJudge#3]
Example to cover some scenarios.

```toml
[fuzz]
exec = ["deno", "run", "fuzz.ts"]
env = { ABC = 2 }

[judge]
exec = ["deno", "run", "validate.ts"]
```

Simple example to static compare

```toml
[judge]
exec = ["diff", "solve.txt", "-"]
```
